### ISSUE TITLE
Can we do a SMILES to Common Chemical Name Translator?

### ISSUE THREAD

**Issue by Sulstice** [Kohulan/Smiles-TO-iUpac-Translator#12]
Hello,

Is it possible to do a SMILES to Common Chemical Name as well as to IUPAC as well? I have the data already available in the form of a name to SMILES directly? Is that possible. 

I will definitely build a connector to this. Been playing with a bit as well. Really like what you have done this is so awesome.

**Comment by Kohulan** [comment]
Current models only support IUPAC name translations. If you have enough data you could retrain the model for common chemical names. 

If the data is open and in public domain I could look into building a model for this.

**Comment by Sulstice** [comment]
https://github.com/Sulstice/global-chem/blob/development/global_chem/global_chem_outputs/global_chem.tsv

So far the data is stored here and is a blend of IUPAC and common chemical names. Some of the names didn't have a common name root. It's still an ongoing curation (will always be) but I am curious as to see what would happen. 

I also don't mind building a model if you teach me what to do! We can maybe collaborate?

**Comment by Kohulan** [comment]
The amount of data you have shared is not enough for training such a model. And it should only contain common names not a mixture of both. If you could get only clean names of more than 10, 000 we could fine-tune the current model and then see how we could proceed further.

**Comment by Sulstice** [comment]
@Kohulan Cool, I have a plan for this so hang tight. I can update you soon.
