### ISSUE TITLE
Conda Package

### ISSUE THREAD

**Issue by ghutchis** [Kohulan/Smiles-TO-iUpac-Translator#14]
Is it possible to get a conda package? This would make it easier to create the conda environment then install this.

**Comment by Kohulan** [comment]
Hi @ghutchis ,
Currently, we do have a PyPi [package](https://pypi.org/project/STOUT-pypi/) . 
```
pip install STOUT-pypi
```

I will look into the conda package and update this issue once it is done.

Kohulan

**Comment by Kohulan** [comment]
Hi @ghutchis 

STOUT can now be installed using conda.

```
conda install -c decimer stout-pypi
```
