### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by Benjaki2** [Kohulan/Smiles-TO-iUpac-Translator#16]
I have been trying to install the package in numerous environments but I keep running into dependency issues. Is there any possibility you would be willing to create a Dockerfile to help simplify the install process?

Thanks thanks for you help and work!

**Comment by PrestonMoak9** [comment]
I've been trying to install this package in so many different environments, but it seems like there are just too many dependency issues to deal with. So, I thought I'd reach out and see if anyone could lend a hand and create a Dockerfile to help make the install process a bit easier.

**Comment by Benjaki2** [comment]
Yeah, I've tried to use PIP and anaconda both. I couldn't get it going on my mac so I also tried it on an ec2 instance. Each case has caused a dependency issue. Most often, the dependency issue is related to tensorflow.

**Comment by Kohulan** [comment]
The Macbook issue might be related to the fact that the new M1 Mac requires a different version of TensorFlow than those found on Linux-based systems. It would be helpful if you could post the entire error log that you are receiving on an EC2 instance.

**Comment by matteoferla** [comment]
For installation on Macs, there is an issue with the dependency JPipe, this requires Java to be installed regardless of what the conda docs say.
For Macs the following works.
```bash
# standard TF installation... will instal TF-Metal:
conda install -c apple tensorflow-deps
pip install tensorflow
# circus
pip install pystow unicodedata2
conda install -c conda-forge jpype1
brew install java
sudo ln -sfn /opt/homebrew/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
pip install STOUT-pypi --no-dependencies
```

**Comment by davidzqhuang** [comment]
Hi all, I don't know how realistic of a solution this is but what I did was to excise the CDK in helpers.py and replace the get_smiles_cdk function with essentially
```
from rdkit import Chem
smiles =  Chem.MolToSmiles(Chem.MolFromSmiles(smiles), isomericSmiles=True, kekuleSmiles=True)
 ```
 
 Below is my Dockerfile, with this Repository cloned at the same level as the Dockerfile
 
 ```
 FROM python:3.8-slim-buster

# Installing gcc, g++
RUN apt-get update && apt-get install -y gcc g++

# Installing necessary packages
RUN pip install tensorflow==2.10.1
RUN pip install rdkit
COPY Smiles-TO-iUpac-Translator /Smiles-TO-iUpac-Translator
RUN pip install -e /Smiles-TO-iUpac-Translator

RUN pip install oloren

RUN python -c "from STOUT import translate_forward, translate_reverse"
# Copying application code to the Docker image
COPY app.py /app.py

# Default command for the container
CMD ["python3.8", "/app.py"]
 ```
 
Here is a link to the repository. Note that this contains a wrapper for my company which is a handler to help deploy it to the serverless cloud, but that code can easily be deleted from the app.py and used as is.

I think the same approach could be used to make a Dockerfile directly for this repository, if the owners are amenable. This would completely avoid any Java dependency. Note I have not extensively tested performance, though its working so far!

**Comment by Kohulan** [comment]
@davidzqhuang ,

Thanks for the input. The sole reason we are using CDK is that we generated the input SMILES using the CDK Canonicalization algorithm. If you use RDKit-generated Canonical SMILES, the IUPAC name may differ from what you want. In addition, the CDK SMILES parser is more tolerant than that of RDKit and we would like to stick with it for these reasons.

If there is sufficient demand for a Docker container in the future, I may create one, however, if you are interested in using STOUT at the moment, please check out our microservice here: https://steinbeck-lab.github.io/cheminformatics-python-microservice/

Kind regards,
Kohulan
