### ISSUE TITLE
PyPi - tensorflow 2.15.0

### ISSUE THREAD

**Issue by Tomisall** [Kohulan/Smiles-TO-iUpac-Translator#24]
Hello, would it be possible to update the pypi requirments to work with tensorflow 2.15.0? When I call `pip install STOUT-pypi==2.0.5` I get `ERROR: Could not find a version that satisfies the requirement tensorflow==2.10.1` 

I'm using Windows 10 and python 3.11.4.

**Comment by Kohulan** [comment]
We must test before updating to the latest Tensorflow version. It's recommended to use Python 3.10 on a Linux environment.

**Comment by Tomisall** [comment]
Thank you Kohulan.
